import { useContext, useState } from "react";
import axios from "axios";
import { AuthContext } from "@/contexts/AuthProvider";
import { useNavigate } from "react-router-dom";

interface FileData {
    userId: string;
    originalName: string;
    s3Key: string;
    contentType: string;
    fileSize: number;
}



interface PresignedUrlResponse {
    url: string;
    UploadedFile: FileData
}


const FileUpload: React.FC = () => {
    const [textExtractionCompleted, setTextExtractionCompleted] = useState(false);
    const auth = useContext(AuthContext);
    if (!auth) {
        throw new Error("Authprovider must be valid");
    }
    const { currUser } = auth;
    console.log(currUser);
    const navigate = useNavigate();

    const [file, setFile] = useState<File | null>(null);
    const [chapter, setChapter] = useState<string>("");
    const [extractedText, setExtractedText] = useState<string>("");
    const [isLoading, setIsLoading] = useState(false);

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files) {
            setFile(e.target.files[0]);
        }
    };

    const handleChapterChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setChapter(e.target.value);
    }

    const handleUploadClick = async () => {
        if (!file) {
            alert("Please select a file to upload");
            return;
        }
        try {
            setIsLoading(true);
            const filename = file.name;
            const contentType = file.type;
            const fileSizeInKb = file.size / 1024;
            const fileSizeInMb = fileSizeInKb / 1024;
            const userId = currUser?.id; // here user id will be the id that is getting generated by cuid();


            const response = await axios.post<PresignedUrlResponse>('http://localhost:7008/pdf/getPresignedUrl', { filename: filename, contentType: contentType, fileSize: fileSizeInMb, userId: userId });
            const { url, UploadedFile } = response.data;
            await uploadFileToS3(file, url);
            await extractTextFromFile(UploadedFile);
        } catch (error) {
            console.error("Error Fetching Presigned Url", error);
        }
    };

    const uploadFileToS3 = async (file: File, url: string) => {
        const formData = new FormData();
        formData.append("file", file);
        try {
            await axios.put(url, formData, {
                headers: {
                    "Content-Type": file.type,
                }
            });
            // alert("file Uploaded Successfully");
        } catch (error) {
            console.log("Error uploading file to s3", error);
            alert("Error uploading file");
        }
    }

    // Add better error handling in extractTextFromFile
    const extractTextFromFile = async (UploadedFile: FileData) => {
        const { s3Key } = UploadedFile;
        try {
            const signedUrlResponse = await axios.post('http://localhost:7008/pdf/getSignedUrlForGetObj', { s3Key });
            const signedUrl = signedUrlResponse.data.url;

            const extractionResponse = await axios.post('http://localhost:5000/extract-text', {
                pdf_url: signedUrl,
                section_type: "Chapter",
                section_number: chapter
            });
            console.log(extractionResponse);

            if (extractionResponse.data.status === 'success') {
                const text = extractionResponse.data.section_text;
                setExtractedText(text);
                setIsLoading(false);
                setTextExtractionCompleted(true);
                console.log(`Extracted ${extractionResponse.data.text_length} characters`);
            } else {
                throw new Error(extractionResponse.data.message);
            }

        } catch (error: any) {
            console.error("Error extracting text:", error);
            setIsLoading(false);
            alert(`Failed to extract text: ${error.response?.data?.message || error.message}`);
        }
    }


    const sendingTextToGeminiToGenerateTest = async (text: string, userId: string) => {
        try {
            const response = await axios.post('http://localhost:7008/tests/generate', { text, userId });
            const testId = response.data.testId;
            setIsLoading(false);
            navigate(`/tests/${testId}/${userId}`, { replace: true });
        } catch (error) {
            console.error("Error generating test");
        }
    }


    const handleGenerateTest = async () => {
        if (extractedText && chapter) {
            const userId: string = currUser?.id!;
            setIsLoading(true);
            await sendingTextToGeminiToGenerateTest(extractedText, userId);
        }
    }


    if (isLoading) {
        return (
            <div className="flex mt-[300px] justify-center w-full ">
                <div className="animate-spin h-16 w-16 border-4 border-blue-500 border-t-transparent rounded-full"></div>
            </div>
        );
    }

    return (
        <div className="flex  justify-center w-full">
            <div className=" mt-[250px]">
                <h1 className="text-3xl font-bold text-center text-gray-800 mb-8">
                    PDF Test Generator
                </h1>
                <div className="space-y-6">
                    {/* Upload PDF Section */}
                    <div>
                        <label className="block text-lg font-semibold text-gray-700 mb-3">
                            Upload Your PDF
                        </label>
                        <input
                            type="file"
                            accept=".pdf"
                            onChange={handleFileChange}
                            className="block w-full px-4 py-3 border border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500"
                        />
                    </div>

                    <div>
                        <label className="block text-lg font-semibold text-gray-700 mb-3">
                            Chapter Number
                        </label>
                        <input
                            type="text"
                            value={chapter}
                            onChange={handleChapterChange}
                            placeholder="Enter chapter number (e.g., Ten, Nine)"
                            className="block w-full px-4 py-3 border border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500"
                        />
                    </div>

                    <button
                        onClick={handleUploadClick}
                        className="w-full bg-Blue text-white py-3 px-6 rounded-lg font-medium text-lg shadow hover:bg-Blue/80 focus:ring focus:ring-blue-300 focus:ring-opacity-50 disabled:bg-gray-400"
                    >
                        Upload File
                    </button>

                    {textExtractionCompleted && (
                        <div className="flex gap-6 justify-center mt-6">
                            <button
                                onClick={handleGenerateTest}
                                className="bg-green-600 text-white py-3 px-6 rounded-lg font-medium text-lg shadow hover:bg-green-700 focus:ring focus:ring-green-300 focus:ring-opacity-50"
                                disabled={!textExtractionCompleted}
                            >
                                Generate Test
                            </button>
                        </div>
                    )}

                </div>
            </div>
        </div>

    )
}

export default FileUpload